(defun test-debug ()
  (princ "Inside test-debug\n")
  (test:clear)
  (princ "After test:clear\n")
  (test:suite 'string)
  (princ "After test:suite\n")
  (test:add-case 'string 'test1 '((lambda () "result")) "result")
  (princ "After test:add-case\n")
  *test-suite*)