* 太阳高度角
简称为“太阳高度”（其实是角度，不是高度）。太阳高度是决定地球表面获得太阳热能数量的最重要的因素。我们用h来表示这个角度，它在数值上等于太阳在地球地平坐标系中的地平高度。

** 一般时间
太阳高度角随着地方时和太阳的赤纬的变化而变化。太阳赤纬（与太阳直射点纬度相等）以δ表示，观测地地理纬度用φ表示（太阳赤纬与地理纬度都是北纬为正，南纬为负），地方时以t表示，有太阳高度角的计算公式：
sin h= sin φ sin δ+cos φ cosδ cos t
** 正午时间
日升日落，同一地点一天内太阳高度角是不断变化的。时角是以正午12点为0度开始算，每一小时为15度。即14点和10点分别为30度和-30度。日出日落时角度都为0，正午时太阳高度角最大（90°），时角为0，以上的公式可以简化为：
sin h=sin φ sin δ+cos φ cos δ
由两角和与差的三角函数公式，可得
sin h=cos(φ－δ)
因此，
对于太阳位于天顶以北的地区而言，h=90°－(φ－δ)；
对于太阳位于天顶以南的地区而言，h=90°－(δ－φ)；
二者合并，因为无论是(φ－δ)还是(δ－φ)，都是为了求当地纬度与太阳直射纬度之差，不会是负的，因此都等于它的绝对值，所以正午太阳高度角计算公式：
h=90°-|φ-δ|
** 具体计算：
还是举个例子来推导，假设春分日（秋分日也可，太阳直射点在赤道）某时刻太阳直射(0°，120°E)这一点，120°E经线上各点都是正午。
对于（0°，120°E）这点来说，它离太阳直射点的纬度距离是0°，它的太阳高度角就是90°。
另外一个观测点，（1°N，120°E）与太阳直射点的纬度差为1°
此时，这一点的太阳高度角为89°（根据上面的公式h=90°-|φ-δ|）。
（1°S，120°E）与太阳直射点的纬度差也是1°.因此，当地的太阳高度角也是89°.
同一时刻，下列各观测点，报告的太阳高度角度数如下：
2°N/S（距太阳直射点2°）：88°=90°－2°
3°N/S（距太阳直射点3°）：87°=90°－3°
10°N/S（距太阳直射点10°）：80°=90°－10°
30°N/S（距太阳直射点30°）：60°=90°－30°
80°N/S（距太阳直射点80°）：10°=90°－80°
90°N/S（距太阳直射点90°）：0°=90°－90°
** 赤纬算法
上述式子中都涉及太阳赤纬，太阳赤纬的算法如下：
由于太阳赤纬角在周年运动中任何时刻的具体值都是严格已知的，所以它（ED）也可
以用与式（1）相类似的表达式表述，即：
ED=0.3723+23.2567sin θ+0.1149sin 2θ－0.1712sin 3θ－0.758cos θ+0.3656cos 2θ+0.0201cos 3θ（5）
式中θ称日角，即 θ=2πt/365.2422（2）
这里t又由两部分组成，即 t=N－N0 （3）
式中N为积日，所谓积日，就是日期在年内的顺序号，例如，1月1日其积日为1，平年12月31日的积日为365，闰年则为366，等等。
N0=79.6764+0.2422×（年份－1985）－INT〔（年份－1985）/4〕
（式中INT表示取整数部分，例如INT(3.25)=3）
* 太阳方位角
太阳方位角是一个地学名词，有其严谨的定义。所谓方位角是以目标物的正北方向（与同一地理分区/分带内所在中央子午线的北方向相同）为起算方向，即0度。其取值范围在0-360度，计算旋转方式为：以目标物为轴心，以目标物的北方向为起始点，按顺时针方向旋转一周，方位角逐步增大至360°。因此太阳方位角一般是以目标物的北方向为起始方向，以太阳光的入射方向为终止方向，按顺时针方向所测量的角度。而正常来说，对于中国区域，早上太阳光从东边射来，中午太阳光从南边射来，傍晚太阳光从西边边射来。早上的太阳方位角在90°左右（但一年当中，有一定的角度范围变化），正中午的太阳方位角在180°（正南方），傍晚的太阳方位角在270°左右(但一年当中，有一定的角度范围变化)。例如北京处在北纬约40°,一年中,早上的太阳方位角变化量约为90°±31°。

对于陆地卫星系统而言，如美国的Landsat TM/ETM+，该卫星的过境（中国）时间大概是早上到中午之间，因此其太阳方位角一般在90°和180°之间。

对于地球上任何位置，当太阳处于春分点或秋分点，即太阳赤纬是0°的时候，初升的太阳方位角是90°整，正午太阳方位角是180°，落日的时候太阳方位角是270°。

对北半球而言，当太阳赤纬大于0°的时候太阳从东偏北方向升起，此时太阳方位角小于90°，中午180°，落日时太阳方位角大于270°。当太阳赤纬小于0°的时候太阳从东偏南方向升起，此时太阳方位角大于90°，中午180°，落日时太阳方位角小于270°。
** 计算
它可以利用下面的公式，经由计算得到良好的近似值，但是因为反正弦值，也就是x = sin(y)有两个以上的解，但只有一个是正确的，所以必需小心的处理。 [1-2]
sin(Φ_s)= -sin(h)cons δ / cos θ_s

下面的两个公式也可以用来计算近似的太阳方位角，不过因为公式是使用余弦函数，所以方位角永远是正值，因此，角度永远被解释为小于180度，而必须依据时角来修正。当在上午时角为负值时 (上午)，方位角的角度小于180度，时角为正值时 (下午)，方位角应该大于180度，即要取补角的值。(大于180度的角没有补角，读者慎重。)

cos(Φ_s)=(sinδcosΦ-coshcosδsinΦ)/cos θ_s

cos(Φ_s)=(sinδ-sin  θ_s sinΦ)/cos θ_s cos Φ 

上述的公式所用的专有名词说明如下：
Φ_s 是太阳的方位角，
θ_s 是太阳高度角，
h 是计算时间的时角，
δ 是当时的太阳赤纬，
Φ 是当地的地理纬度。
* 时角
时角定义为天子午圈与天体的赤经圈在北极所成的球面角，或在天赤道上所夹的弧度。由于地球的自转，天体的时角每小时（恒星小时）增长15°。因此天体的时角通常采用相应的时间单位，以0~24时取代0°~360°；以1时取代15°；以1分取代15'。 [1]

一个天体的时角也可以表示该天体是否通过了当地的子午圈（中天）。时角的数值表示了该天体与当地子午圈的角距离，例如，一个天体的时角是2.5时，就表示它已经在2.5小时之前通过当地的子午圈，并且现在时刻在当地子午圈向西方向37.5°的角距离上。

当时角在180°以内时，该天体的位置必定在观测者子午线的西方；如果时角超过180°，则天体必定在观测者子午线的东方。即时角在0°~180°时，天体的方位角在西方；时角在180°~360°时，天体的方位角便在东方。
