(defun matrix:v^v (u v)
    "两向量的叉积"
    (list (- (* (cadr u)
                (caddr v))
            (* (cadr v)
                (caddr u)))
        (- (* (car v)
                (caddr u))
            (* (car u)
                (caddr v)))
        (- (* (car u)
                (cadr v))
            (* (car v)
                (cadr u)))))
