(defun block:get-attributes (blk / lst)
  "获取块属性,返回属性名和值的点对列表。"
  (if (= (quote ename)
	 (type blk))
      (setq blk (e2o blk)))
  (if (= 'vla-object (type blk))
      (if (safearray-value (setq lst (vlax-variant-value (vla-getattributes blk))))
	  (mapcar (quote (lambda (x)
			   (cons (vla-get-tagstring x)
				 (vla-get-textstring x))))
		  (vlax-safearray->list lst)))
      nil))
