(defun block:get-attributes (blkref / lst)
  "获取块属性,返回属性名和值的点对列表。"
  (if (= (quote ename)
	 (type blkref))
      (setq blkref (e2o blkref)))
  (if (= 'vla-object (type blkref))
      (if (safearray-value (setq lst (vlax-variant-value (vla-getattributes blkref))))
	  (mapcar (quote (lambda (x)
			   (cons (vla-get-tagstring x)
				 (vla-get-textstring x))))
		  (vlax-safearray->list lst)))
      nil))
