(defun block:get-dynamic-prop-cons-name-value (blk / props n lst)
  "获取动态块的动态特性(自定义)列表：特性名与当前值的点对表"
  (setq props (block:get-dynamic-properties blk))
  (setq n 0)
  (setq lst nil)
  (repeat (length (car props))
    (setq lst (append lst (list (cons (nth n (car props))
            (nth n (cadr props))))))
    (setq n (1+ n)))
  lst)
