(defun curve:lwpl-is-circle-p (ent / vertexs bulges flag o)
  "检测多段线是否为圆"
  "T or nil"
  (setq vertexs (curve:pline-3dpoints ent))
  (setq bulges (curve:pline-convexity ent))
  (if (> (length vertexs)
      (length bulges))
    (setq vertexs (reverse (cdr (reverse vertexs)))))
  (setq flag t)
  (setq o (curve:bulge2o (car vertexs)
      (cadr vertexs)
      (car bulges)))
  (repeat (length vertexs)
    (if (> (distance o (curve:bulge2o (car vertexs)
            (cadr vertexs)
            (car bulges)))
        0.001)
      (setq flag nil))
    (setq vertexs (append (cdr vertexs)
        (list (car vertexs))))
    (setq bulges (append (cdr bulges)
        (list (car bulges)))))
  flag)
