(defun geometry:on-segment (pt segment)
  "判断一个与线段共线的点是否在线段上。"
  (and (>= (car pt)
      (apply (quote min)
        (mapcar (quote car)
          segment)))
    (<= (car pt)
      (apply (quote max)
        (mapcar (quote car)
          segment)))
    (>= (cadr pt)
      (apply (quote min)
        (mapcar (quote cadr)
          segment)))
    (<= (cadr pt)
      (apply (quote max)
        (mapcar (quote cadr)
          segment)))))
