(defun m:base->dec (n b / l)
    "进制转换"
    (if (= 1 (setq l (strlen n)))
        (- (ascii n)
            (if (< (ascii n)
                    65)
                48 55))
        (+ (* b (m:base->dec (substr n 1 (1- l))
                    b))
            (m:base->dec (substr n l)
                b))))
