(defun m:coord-chg (pt-wcs o-ucs o-ang / pt1a x y z)
    (setq pt1a (mapcar (quote -)
            pt-wcs o-ucs))
    (setq x (car pt1a))
    (setq y (cadr pt1a))
    (list (+ (* x (car o-ang))
            (* y (cadr o-ang)))
        (- (* y (car o-ang))
            (* x (cadr o-ang)))
        0))
