(defun pickset:getbox (ss offset / ptlist)
  "获取选择集的包围盒。"
  "外框（偏移后）的左下，右上角点"
  "(pickset:getbox sel 0.2)"
  (if (= (quote pickset)
      (type ss))
    (setq ptlist (apply (quote append)
        (mapcar (quote (lambda (x)
              (entity:getbox x offset)))
          (pickset:to-list ss))))
    (setq ptlist (apply (quote append)
        (mapcar (quote (lambda (x)
              (entity:getbox x offset)))
          ss))))
  (list (apply (quote mapcar)
      (cons (quote min)
        ptlist))
    (apply (quote mapcar)
      (cons (quote max)
        ptlist))))
