(defun vectra:xprop-pack1 (kv xdatatypes / code name value)
  (setq name (car kv)
    value (cdr kv))
  (or (setq code (cdr (assoc name xdatatypes)))
    (setq code (cdr (assoc (type value)
          (quote ((str . 1000)
              (int . 1070)
              (real . 1040)
              (list . 1010)))))))
  (list (cons 1000 name)
    (cons code value)))
