(defun vectra:make-sharparc (p r a4 a5)
  (if (or (and (> a5 a4)
        (< (- a5 a4)
          pi))
      (and (< a5 a4)
        (> (- a4 a5)
          pi)))
    (vectra:make-arc p r a4 a5)
    (vectra:make-arc p r a5 a4)))
