(defun vectra:get-bulge (v1 v2 / a1 a2 bulge dot)
  (setq dot (sp-dotproduct v1 v2)
    a1 (sp-angle v1)
    a2 (sp-angle v2))
  (if (< dot 0)
    (setq bulge (tan (/ (acos (abs dot))
          4.0)))
    (setq bulge (tan (/ (- pi (acos (abs dot)))
          4.0))))
  (setq a2 (- a2 a1))
  (if (or (and (>= a2 0)
        (< a2 pi))
      (and (< a2 0)
        (< a2 (- pi))))
    (setq bulge (- bulge)))
  bulge)
