(defun vectra:commandrun (func / *error*)
  (defun *error* (s)
    (vectra:error-handler s))
  (vectra:error-start0)
  (vectra:startundomark)
  (eval func)
  (vectra:endundomark)
  (vectra:error-end)
  (princ))
