(defun vectra:make-setenv (vars / rv)
  (setq rv (list $addnew-layer $addnew-color $addnew-linetype $addnew-lineweight $addnew-textstyle $addnew-block-base))
  (vectra:set-symbol-notnull (quote $addnew-layer)
    (car vars))
  (vectra:set-symbol-notnull (quote $addnew-color)
    (cadr vars))
  (vectra:set-symbol-notnull (quote $addnew-linetype)
    (caddr vars))
  (vectra:set-symbol-notnull (quote $addnew-lineweight)
    (cadddr vars))
  (vectra:set-symbol-notnull (quote $addnew-textstyle)
    (car (cddddr vars)))
  (vectra:set-symbol-notnull (quote $addnew-block-base)
    (cadr (cddddr vars)))
  rv)
